import fs from 'node:fs';
import { createHash } from 'node:crypto';
import { updatesPanel, ticker, scrollControls } from './components.mjs';
import { seo, faqMarkup } from './seo.mjs';
const assetVersion=createHash('sha256').update(['style.css','modern.css','site.js','announcements.js'].map(file=>fs.readFileSync('dist/assets/'+file,'utf8')).join('\n')).digest('hex').slice(0,12);
const origin=new URL(process.env.SITE_URL || process.argv.find(x=>x.startsWith('--origin='))?.slice(9) || 'https://psb-associates-redesign.choudharidarshan556.chatgpt.site').origin;
const practices=[
{slug:'audit-assurance',name:'Audit & Assurance',short:'Independent assurance. Informed oversight.',desc:'Audit and assurance services that support regulatory compliance, reliable financial reporting and a clearer understanding of your business.',items:['Statutory audits under Indian and International GAAP','Internal audits and control reviews','Tax audits','Systems and management audits','Agreed upon procedures','Certification services and special audits','Stock and trust audits','Foreign exchange remittance certifications — Forms 15CA / 15CB'],focus:'Our approach considers the business environment alongside the financial statements. We review processes, controls and reporting to identify matters that require attention and communicate our findings clearly.'},
{slug:'taxation',name:'Direct & Indirect Taxation',short:'Clarity in a changing tax environment.',desc:'Tax planning, compliance and advisory for domestic and international transactions, with support across income tax, GST and transfer pricing.',items:['Income tax planning and compliance','GST and indirect taxation advisory','Tax and statutory compliance reviews','Domestic and international transfer pricing','International taxation and cross-border transaction advisory','Tax due diligence','Representations and litigation support','Investigation and special purpose audits','Regulatory support under FEMA and RBI guidelines'],focus:'We help clients understand their obligations, evaluate the tax implications of transactions and prepare for compliance. Our partners bring direct involvement to complex matters and representations.'},
{slug:'corporate-advisory',name:'Corporate Advisory & Startups',short:'A considered foundation for what comes next.',desc:'Support for business formation, corporate compliance, financing and transactions, shaped around the needs of established businesses and new ventures.',items:['Company formation and business setup','Corporate secretarial services and company law consultancy','Project financing and private equity funding support','Mergers and acquisitions','Due diligence and arbitration','Business and share valuation','Monitoring of funds management','Review and structuring of financial and managerial resources','IFRS and Ind AS convergence','IFRS valuation services'],focus:'From establishing the right business structure to evaluating a transaction, we bring accounting, financial and regulatory perspectives together. Each engagement begins with an understanding of your circumstances and objectives.'},
{slug:'accounting-outsourcing',name:'Accounting & Virtual CFO',short:'Reliable information. Practical financial oversight.',desc:'Accounting, payroll and management reporting support, complemented by financial planning and business intelligence services.',items:['Bookkeeping and ledger scrutiny','Accounting and payroll outsourcing','Management information system (MIS) reporting','Virtual CFO and financial planning support','Design of accounting and management information systems','Data analytics and research','Computer assisted audit techniques (CAAT)','Enterprise architecture and implementation reviews','IT infrastructure and network consultancy','Systems and software remediation','Resource and capacity assessment','Business process outsourcing (BPO) operations'],focus:'We organise financial information into useful reporting for management. Accounting and outsourcing support can be combined with process reviews, analytics and financial oversight according to the scope of the engagement.'}
];
const partners=[
{slug:'pavan-toshniwal',name:'CA Pavan S. Toshniwal',role:'Founding Partner',qual:'M.Com., FCA, DISA',image:'pavan',focus:'Income tax · International tax · Transfer pricing',bio:'A Fellow member of the Institute of Chartered Accountants of India and an Information System Auditor (DISA), Pavan Toshniwal is a founding partner of the firm. His areas of practice include international tax, income tax, transfer pricing, indirect tax and assurance. He is also involved in project financing and private equity funding services.'},
{slug:'bharadwaj-mandhane',name:'CA Bharadwaj R. Mandhane',role:'Founding Partner',qual:'B.Com., FCA',image:'bharadwaj',focus:'Indirect tax · Assurance · Business setup',bio:'Bharadwaj Mandhane is a founding partner and a Fellow member of the Institute of Chartered Accountants of India. He heads the indirect tax and assurance practice, with experience serving corporate and multinational clients across industries. His work also includes tax and financial planning, and business setup services.'},
{slug:'sagar-nikam',name:'CA Sagar Sahebrao Nikam',role:'Partner',qual:'Chartered Accountant · M. No. 641644',image:'sagar',focus:'Member of the partner team',bio:'CA Sagar Sahebrao Nikam is a partner at P S B & Associates LLP and a member of the Institute of Chartered Accountants of India, with membership number 641644. He joins the partner team in the firm’s accounting, tax, assurance and advisory practice.'}
];
partners.sort((a,b)=>['pavan','sagar','bharadwaj'].indexOf(a.image)-['pavan','sagar','bharadwaj'].indexOf(b.image));
const sectors=['Software & Information Technology','Engineering','Travel & Hospitality','Education','Banking & Financial Services','NGOs & Public Trusts'];
const disclaimer='As per the rules of the Institute of Chartered Accountants of India (ICAI), Chartered Accountants are not permitted to advertise or solicit work. This website is meant solely for the purpose of providing information about the firm and its members.';
const link=(href,text,style='text-link')=>`<a class="${style}" href="${href}">${text}</a>`;
const brand=`<a class="brand" href="/" aria-label="P S B & Associates LLP home"><strong>PSB<span>&</span></strong><div>P S B & Associates LLP<small>CHARTERED ACCOUNTANTS</small></div></a>`;
const serviceIcons=['<path d="M12 3 4 6v6c0 5 8 9 8 9s8-4 8-9V6z"/><path d="m8 12 3 3 5-6"/>','<rect x="4" y="3" width="16" height="18" rx="2"/><path d="M8 7h8M8 11h2m4 0h2m-8 4h2m4 0h2M8 18h2m4 0h2"/>','<path d="M3 21h18M5 21V8l7-5 7 5v13M9 21v-5h6v5M9 9h.01M15 9h.01M9 12h.01M15 12h.01"/>','<path d="M3 20h18M6 16v-4m6 4V8m6 8V4"/>'];
const cards=()=>`<div class="practice-grid" tabindex="0" aria-label="Practice areas">${practices.map((p,i)=>`<a class="practice-card" href="/services/${p.slug}/"><div class="practice-top"><span class="number">0${i+1} / 04</span><svg class="service-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.25" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${serviceIcons[i]}</svg></div><h3>${p.name}</h3><p>${p.desc}</p><div class="practice-tags">${p.items.slice(0,2).map(x=>`<span>${x.replace(' under Indian and International GAAP','').replace(' and control reviews','')}</span>`).join('')}</div><span class="card-link">Explore practice</span></a>`).join('')}</div>`;
const people=()=>`<div class="people-grid">${partners.map(p=>`<a class="person" href="/partners/${p.slug}/"><div class="portrait"><img src="/assets/${p.image}.webp" alt="${p.name}" loading="lazy"></div><div class="person-meta"><span>${p.role}</span><h3>${p.name}</h3><p>${p.qual}</p><span class="profile-link">View profile</span></div></a>`).join('')}</div>`;
const strip=`<div class="firm-strip"><div><strong>2013</strong><span>Established</span></div><div><strong>12+</strong><span>Years of firm practice</span></div><div><strong>03</strong><span>Partners</span></div><div><strong>02</strong><span>Offices in Maharashtra</span></div></div>`;
const contactBand=`<section class="contact-band wrap"><div><span class="eyebrow">GET IN TOUCH</span><h2>A conversation starts<br>with understanding.</h2></div><div><p>Contact our offices to discuss your accounting, tax, assurance or advisory requirements.</p>${link('/contact/','Contact the firm','button light')}</div></section>`;
function shell(title,desc,body,current='home',route='/'){
const nav=[['home','/','Home'],['about','/about/','The Firm'],['services','/services/','Our Expertise'],['partners','/partners/','Our People'],['industries','/industries/','Industries'],['resources','/resources/','The Briefing']];
return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">${seo(origin,route,title,desc)}<meta name="theme-color" content="#10273b"><link rel="icon" type="image/png" href="/assets/brand-icon.png"><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700&family=Manrope:wght@400;500;600;700;800&display=swap" rel="stylesheet"><link rel="stylesheet" href="/assets/style.css?v=${assetVersion}"><link rel="stylesheet" href="/assets/modern.css?v=${assetVersion}"><script src="/assets/site.js?v=${assetVersion}" defer></script><script src="/assets/announcements.js?v=${assetVersion}" defer></script></head><body class="page-${current}"><div class="reading-progress" aria-hidden="true"></div><a class="skip" href="#main">Skip to content</a><header><div class="nav-wrap">${brand}<button class="menu-toggle" aria-label="Toggle navigation" aria-controls="navigation" aria-expanded="false">Menu <span>☰</span></button><nav id="navigation" aria-label="Main navigation">${nav.map(([key,href,label])=>`<a href="${href}" ${current===key?'aria-current="page"':''}>${label}</a>`).join('')}${link('/contact/','Contact us','nav-contact')}</nav></div></header><main id="main">${body}</main><footer><div class="wrap footer-grid"><div>${brand}<p>Accounting, tax, audit and advisory.<br>Partner-led practice since 2013.</p></div><div><h3>Explore</h3>${nav.slice(1).map(([,href,label])=>link(href,label,'')).join('')}</div><div><h3>Practice areas</h3>${practices.map(p=>link('/services/'+p.slug+'/',p.name,'')).join('')}</div><div><h3>Contact</h3>${link('mailto:office@psbassociates.in','office@psbassociates.in','')}${link('tel:+919922412220','+91 99224 12220','')}<p>Mon–Sat · 10:30 AM–7:30 PM</p>${link('/contact/','Our offices','')}</div></div><div class="wrap footer-bottom"><p>${disclaimer}</p><div><span>© <span data-year>2026</span> P S B & Associates LLP</span><div>${link('/privacy/','Privacy notice','')}${link('/disclaimer/','Disclaimer','')}</div></div></div></footer></body></html>`;
}
const intro=(tag,title,desc)=>`<section class="page-intro wrap"><span class="eyebrow">${tag}</span><h1>${title}</h1><p>${desc}</p></section>`;
function save(route,title,desc,body,current){const dir='dist'+route;fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(dir+'index.html',shell(title,desc,body,current,route));}
save('/','Chartered Accountants in Chhatrapati Sambhajinagar & Hingoli','P S B & Associates LLP: audit, taxation, corporate advisory and accounting services. Partner-led practice in Chhatrapati Sambhajinagar and Hingoli since 2013.',`
<section class="hero hero-modern"><div class="hero-grid" aria-hidden="true"></div><div class="wrap hero-inner"><div class="hero-copy"><h1>Clarity for today.<br>Confidence for<br><em>what’s next.</em></h1><p>Accounting, assurance and advisory with a deeper understanding of your business.</p><div class="hero-actions">${link('/services/','Explore our expertise','button gold')}${link('/about/','Discover PSB','button outline')}</div><div class="hero-signature"><span>EST. <b>2013</b></span><p>Partner-led. Principle-driven.<br>Chhatrapati Sambhajinagar & Hingoli.</p></div></div>${updatesPanel({compact:true})}</div><div class="hero-base wrap"><span>YOUR BUSINESS. OUR COLLECTIVE PERSPECTIVE.</span><a href="#firm">EXPLORE THE FIRM <span>↓</span></a></div></section>${ticker}
${strip}<section class="wrap firm-section" id="firm"><div><span class="eyebrow">THE FIRM</span><h2>Expertise grounded<br>in your business.</h2></div><div><p class="lead">A full-service accounting, tax and audit firm, built on professional integrity and personal involvement.</p><p>Established in 2013, P S B & Associates LLP brings together chartered accountants and professionals under the guidance of its partners. From statutory obligations to financial decisions, our work begins with understanding your business.</p>${link('/about/','More about PSB')}</div></section>
<section class="expertise-section"><div class="wrap"><div class="section-head"><div><span class="eyebrow">OUR EXPERTISE</span><h2>Connected expertise.<br>A considered approach.</h2></div><p>Four practice areas bring together the services your business needs, with partner involvement throughout.</p></div>${cards()}${scrollControls}</div></section>
<section class="values-section wrap"><span class="eyebrow">HOW WE WORK</span><div class="values-layout"><h2>Principles that guide<br>our practice.</h2><div class="values-list"><article><span>01</span><div><h3>Professional integrity</h3><p>Objective judgement, confidentiality and a commitment to ethical professional conduct.</p></div></article><article><span>02</span><div><h3>Partner-led attention</h3><p>Experienced partners guide our teams and remain involved in the matters that need their expertise.</p></div></article><article><span>03</span><div><h3>Time-bound execution</h3><p>Structured processes, careful preparation and clear communication help keep engagements on track.</p></div></article></div></div></section>
<section class="people-section"><div class="wrap"><div class="section-head"><div><span class="eyebrow">OUR PEOPLE</span><h2>Experience with<br>a personal perspective.</h2></div>${link('/partners/','Meet the partners')}</div>${people()}</div></section>
<section class="wrap industries-home"><div><span class="eyebrow">INDUSTRIES WE SERVE</span><h2>Understanding the context.<br>Seeing the detail.</h2><p>Our practice serves corporates, financial institutions, startups, individuals and nonprofit organisations.</p>${link('/industries/','Explore industry experience')}</div><div class="sector-list">${sectors.map((s,i)=>`<span><small>0${i+1}</small>${s}</span>`).join('')}</div></section>${faqMarkup}${contactBand}`,'home');
save('/about/','The Firm','Learn about P S B & Associates LLP, its practice since 2013, professional values and offices in Maharashtra.',`${intro('THE FIRM','Built on integrity.<br>Focused on understanding.','A partner-led practice bringing accounting, tax, audit and financial advisory together since 2013.')}<section class="wrap about-body"><div class="about-photo"><img src="/assets/office.jpg" alt="Business professionals working together" loading="lazy"><span>COLLABORATION AT THE CORE OF OUR PRACTICE</span></div><div><h2>A practical perspective,<br>backed by experience.</h2><p>P S B & Associates LLP was established in 2013 by founding partners CA Pavan S. Toshniwal and CA Bharadwaj R. Mandhane. CA Sagar Sahebrao Nikam is the third member of the partner team.</p><p>The firm provides services to clients in India and abroad. Our team of chartered accountants and other professionals works under partner guidance across assurance, accounting and payroll outsourcing, tax planning, financial planning, company formation, business setup and financing.</p><p>With offices in Chhatrapati Sambhajinagar and Hingoli, our practice serves Indian and multinational corporates, banking and financial institutions, startups, high-net-worth individuals, executives and expatriates.</p></div></section>${strip}<section class="wrap values-section"><div class="section-head"><div><span class="eyebrow">OUR APPROACH</span><h2>Careful work.<br>Clear communication.</h2></div></div><div class="three-col"><article><h3>Understand</h3><p>We begin with your business, industry and the specific requirements of the engagement.</p></article><article><h3>Evaluate</h3><p>We bring accounting, regulatory and financial perspectives to the questions at hand.</p></article><article><h3>Communicate</h3><p>We explain findings, requirements and next steps so you can make informed decisions.</p></article></div></section>${contactBand}`,'about');
save('/services/','Our Expertise','Explore audit and assurance, direct and indirect taxation, corporate advisory, startup, accounting, virtual CFO and business intelligence services.',`${intro('OUR EXPERTISE','A complete view<br>of your financial world.','Accounting, assurance, taxation and advisory services, organised around your business needs.')}<section class="wrap service-index">${cards()}<div class="note"><h3>Business intelligence, integrated.</h3><p>Our accounting and advisory practice also includes MIS design, data analytics, computer assisted audit techniques, technology reviews and business process outsourcing.</p></div></section>${contactBand}`,'services');
for(const [i,p]of practices.entries())save('/services/'+p.slug+'/',p.name,p.desc,`${intro('OUR EXPERTISE / 0'+(i+1),p.name,p.short)}<section class="wrap detail-layout"><aside><span class="eyebrow">PRACTICE AREAS</span>${practices.map(q=>`<a ${p===q?'aria-current="page"':''} href="/services/${q.slug}/">${q.name}</a>`).join('')}${link('/contact/','Contact our team','button navy')}</aside><div><p class="lead">${p.desc}</p><h2>Scope of services</h2><div class="service-list">${p.items.map((item,j)=>`<div><span>${String(j+1).padStart(2,'0')}</span>${item}</div>`).join('')}</div><h2>Our approach</h2><p>${p.focus}</p><details><summary>How is the scope of an engagement determined?</summary><p>Services are agreed based on your requirements, applicable professional standards and the circumstances of the matter. Contact the firm to discuss the relevant scope and documentation.</p></details><details><summary>Can related practice areas be combined?</summary><p>Yes. Depending on the engagement, our partners can coordinate accounting, tax, assurance and advisory expertise, subject to applicable independence and professional requirements.</p></details></div></section>${contactBand}`,'services');
save('/partners/','Our People','Meet CA Pavan S. Toshniwal, CA Bharadwaj R. Mandhane and CA Sagar Sahebrao Nikam, partners at P S B & Associates LLP.',`${intro('OUR PEOPLE','Partner-led.<br>Personally involved.','Three chartered accountants bringing professional judgement and direct involvement to the firm’s practice.')}<section class="wrap partners-index">${people()}</section>${contactBand}`,'partners');
for(const p of partners)save('/partners/'+p.slug+'/',p.name,p.qual+' — '+p.role+' at P S B & Associates LLP.',`<section class="wrap partner-profile"><div class="portrait"><img src="/assets/${p.image}.webp" alt="${p.name}"></div><div><span class="eyebrow">${p.role}</span><h1>${p.name}</h1><p class="qualification">${p.qual}</p><div class="profile-rule"></div><span class="eyebrow">PROFESSIONAL PROFILE</span><p class="lead">${p.bio}</p><p>${p.focus}</p><div class="hero-actions">${link('/contact/','Contact the firm','button navy')}${link('/partners/','All partners')}</div></div></section>`,'partners');
save('/industries/','Industries','PSB serves IT, engineering, hospitality, education, banking, financial services, NGOs and public trusts.',`${intro('INDUSTRIES','Sector context.<br>Professional perspective.','Our practice spans businesses, institutions and individuals, with attention to the operating environment of each engagement.')}<section class="wrap industry-grid">${sectors.map((s,i)=>`<article><span class="number">0${i+1}</span><h2>${s}</h2><p>${['Accounting, taxation and assurance for software and technology businesses, including corporate and multinational operations.','Financial reporting, audit and advisory for engineering businesses and their operating requirements.','Accounting, payroll, taxation and business advisory for travel and hospitality operations.','Assurance, financial reporting and compliance support for educational institutions.','Audit, taxation and financial advisory for banking and financial institutions.','Trust audits, accounting and compliance support for nongovernment organisations and public trusts.'][i]}</p></article>`).join('')}</section><section class="wrap audience-note"><span class="eyebrow">BEYOND SECTORS</span><h2>Businesses and the people behind them.</h2><p>We also serve startups, high-net-worth individuals, executives and expatriates, alongside Indian and multinational corporates.</p></section>${contactBand}`,'industries');
save('/resources/','The PSB Briefing','Latest official announcements from GST, Income Tax, ICAI and RBI, with automatic updates, search and category filters.',`${intro('THE PSB BRIEFING','Stay ahead<br>of what matters.','Official announcements, regulatory developments and professional resources. Automatically brought together for a clearer perspective.')}<section class="wrap briefing-section" id="announcements">${updatesPanel()}</section><section class="wrap resource-grid">${[['Income Tax Department','Income tax information, filing services and departmental notifications.','https://www.incometax.gov.in/'],['GST Portal','GST registration, returns and official taxpayer services.','https://www.gst.gov.in/'],['Ministry of Corporate Affairs','Corporate filings, company information and MCA updates.','https://www.mca.gov.in/'],['Institute of Chartered Accountants of India','Professional publications, standards and institute announcements.','https://www.icai.org/'],['Reserve Bank of India','RBI notifications, directions and foreign exchange information.','https://www.rbi.org.in/'],['Central Board of Indirect Taxes & Customs','Official indirect tax and customs notifications and circulars.','https://www.cbic.gov.in/']].map(([name,desc,url])=>`<a class="resource" href="${url}" target="_blank" rel="noopener noreferrer"><span class="eyebrow">OFFICIAL PORTAL</span><h2>${name}</h2><p>${desc}</p><span class="card-link">Visit website <span class="sr-only">(opens in a new tab)</span></span></a>`).join('')}</section><div class="wrap note"><p>Read the original announcement for full context and applicability. Headlines are information from external sources, not advice from PSB. The feed checks official sources every 15 minutes while this page is open.</p></div>${contactBand}`,'resources');
const offices=[{city:'Chhatrapati Sambhajinagar',type:'HEAD OFFICE',address:'Office No. 5 & 6, next to CIDCO Bus Stand,<br>Jalgaon Road, N-1, CIDCO,<br>Chhatrapati Sambhajinagar, Maharashtra.',phones:['9922412220','9422868050'],map:'Office No 5 6 Next to CIDCO Bus Stand N1 Jalgaon Road Chhatrapati Sambhajinagar'},{city:'Hingoli',type:'BRANCH OFFICE',address:'Shop No. 18 & 19, Municipal Shopping Complex,<br>near Peoples Co-Op. Bank, Akola Road,<br>Hingoli, Maharashtra – 431513.',phones:['9403806446'],map:'Municipal Shopping Complex Peoples Cooperative Bank Akola Road Hingoli'}];
save('/contact/','Contact & Offices','Contact PSB Associates offices in Chhatrapati Sambhajinagar and Hingoli. Email office@psbassociates.in or call +91 9922412220.',`${intro('CONTACT & OFFICES','Here to understand<br>your requirements.','Reach our team in Chhatrapati Sambhajinagar or Hingoli.')}<section class="wrap offices-grid">${offices.map(o=>`<article><span class="eyebrow">${o.type}</span><h2>${o.city}</h2><p>${o.address}</p><div class="phones">${o.phones.map(n=>link('tel:+91'+n,'+91 '+n,'')).join('')}</div>${link('https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(o.map),'View directions')}<iframe title="Map of ${o.city} office area" loading="lazy" referrerpolicy="no-referrer-when-downgrade" src="https://maps.google.com/maps?q=${encodeURIComponent(o.map)}&output=embed"></iframe></article>`).join('')}</section><section class="wrap inquiry-section"><div><span class="eyebrow">WRITE TO US</span><h2>Share the context.<br>We’ll take it from there.</h2><p>${link('mailto:office@psbassociates.in','office@psbassociates.in','contact-email')}</p><p>Monday–Saturday<br>10:30 AM–7:30 PM IST</p><p class="muted">This form prepares a draft in your email application. Your inquiry is delivered when you send that email. Please avoid including confidential documents or sensitive financial information.</p></div><form id="inquiry"><div class="form-row"><label>Your name<input name="name" autocomplete="name" required maxlength="120"></label><label>Email address<input type="email" name="email" autocomplete="email" required maxlength="200"></label></div><label>Area of interest<select name="service" required><option value="">Select a practice area</option>${practices.map(p=>`<option>${p.name}</option>`).join('')}<option>General inquiry</option></select></label><label>How can we help?<textarea name="message" rows="5" required maxlength="3000"></textarea></label><label class="checkbox"><input type="checkbox" required><span>I have read the <a href="/disclaimer/">professional disclaimer</a> and <a href="/privacy/">privacy notice</a>.</span></label><button type="submit" class="button navy">Prepare email inquiry</button><p id="form-status" role="status" aria-live="polite"></p></form></section>`,'contact');
save('/disclaimer/','Professional Disclaimer','Professional and informational disclaimer for the PSB Associates website.',`${intro('PROFESSIONAL DISCLAIMER','Information with<br>a clear purpose.','Please read this notice when using this website.')}<section class="wrap legal"><p class="lead">${disclaimer}</p><h2>General information</h2><p>The content is provided for general informational purposes and does not constitute professional advice or create a professional engagement. Obtain advice appropriate to your specific circumstances before making decisions.</p><h2>External information</h2><p>Laws, regulations and guidance can change. External portals are provided for reference; the firm does not control their content or availability.</p></section>`,'');
save('/privacy/','Privacy Notice','How the PSB Associates informational website handles inquiries and external services.',`${intro('PRIVACY NOTICE','Respect for your<br>information.','A straightforward explanation of this website’s functionality.')}<section class="wrap legal"><h2>Inquiries</h2><p>The inquiry form prepares an email draft on your device. It does not store submissions in a website database. Information is sent to the firm only when you send the draft through your email provider. Contact office@psbassociates.in with questions about information you send to the firm.</p><h2>External services</h2><p>Google Maps is embedded on the contact page, and typefaces load from Google Fonts. These providers may receive your IP address and browser information when their content loads. Official resource links open third-party sites with their own privacy practices.</p><h2>Confidential information</h2><p>Please do not send confidential financial records or identity documents through a general website inquiry. Appropriate arrangements can be discussed directly with the firm.</p></section>`,'');
fs.writeFileSync('dist/robots.txt','User-agent: *\nAllow: /\nSitemap: '+origin+'/sitemap.xml\n');
const routes=['/','/about/','/services/','/partners/','/industries/','/resources/','/contact/','/privacy/','/disclaimer/',...practices.map(p=>'/services/'+p.slug+'/'),...partners.map(p=>'/partners/'+p.slug+'/')];
fs.writeFileSync('dist/sitemap.xml','<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+routes.map(r=>'<url><loc>'+origin+r+'</loc></url>').join('')+'</urlset>');
console.log('Built '+routes.length+' complete pages.');

await import('./scripts/build-worker.mjs');
