export const faqs=[
 ['What services does PSB Associates provide?','P S B & Associates LLP provides audit and assurance, income tax and GST compliance, corporate advisory, business setup, accounting outsourcing, payroll, MIS reporting and virtual CFO services.'],
 ['Where are PSB Associates offices located?','The firm has its head office in Chhatrapati Sambhajinagar and a branch office in Hingoli, Maharashtra. Office addresses and directions are available on the Contact page.'],
 ['Does PSB work with startups and companies?','Yes. The firm supports startups, Indian and multinational companies, financial institutions, individuals, NGOs and public trusts. Engagement scope is agreed according to each client’s requirements.'],
 ['How can I contact PSB Associates?','Email office@psbassociates.in or call +91 99224 12220. Office hours are Monday to Saturday, 10:30 AM to 7:30 PM IST.'],
 ['Where does the PSB Briefing get its updates?','The Briefing checks the official GST, Income Tax, ICAI and RBI announcement sources. Each item links to its official source and shows the publication date when available. Refresh checks all four sources immediately; unavailable sources retain clearly marked previously checked information.']
];
export const faqMarkup=`<section class="wrap faq-section"><span class="eyebrow">USEFUL ANSWERS</span><h2>About our practice.</h2>${faqs.map(([q,a])=>`<details><summary>${q}</summary><p>${a}</p></details>`).join('')}<a class="text-link" href="/contact/">Office addresses and contact details</a></section>`;
export function seo(origin,route,title,description){
 const name='P S B & Associates LLP';
 const headline=route==='/'?'PSB Associates | Chartered Accountants, Tax & Audit':`${title} | ${name}`;
 const firm={'@type':'AccountingService','@id':origin+'/#firm',name,alternateName:'PSB Associates',url:origin+'/',logo:origin+'/assets/brand-icon.png',image:origin+'/assets/social-preview.png',description:'Chartered accountants providing audit, income tax, GST, accounting and corporate advisory services since 2013.',foundingDate:'2013',telephone:'+91-9922412220',email:'office@psbassociates.in',address:{'@type':'PostalAddress',streetAddress:'Office No. 5 & 6, next to CIDCO Bus Stand, Jalgaon Road, N-1, CIDCO',addressLocality:'Chhatrapati Sambhajinagar',addressRegion:'Maharashtra',addressCountry:'IN'},areaServed:['Chhatrapati Sambhajinagar','Hingoli','India'],openingHoursSpecification:{'@type':'OpeningHoursSpecification',dayOfWeek:['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'],opens:'10:30',closes:'19:30'},department:{'@type':'AccountingService',name:name+' — Hingoli office',address:{'@type':'PostalAddress',streetAddress:'Shop No. 18 & 19, Municipal Shopping Complex, near Peoples Co-Op. Bank, Akola Road',addressLocality:'Hingoli',addressRegion:'Maharashtra',postalCode:'431513',addressCountry:'IN'},telephone:'+91-9403806446'}};
 const graph=[firm,{'@type':'WebSite','@id':origin+'/#website',name,url:origin+'/',publisher:{'@id':firm['@id']}},{'@type':'WebPage','@id':origin+route+'#webpage',url:origin+route,name:headline,description,inLanguage:'en-IN',isPartOf:{'@id':origin+'/#website'},about:{'@id':firm['@id']}}];
 if(route!=='/')graph.push({'@type':'BreadcrumbList',itemListElement:[{'@type':'ListItem',position:1,name:'Home',item:origin+'/'},{'@type':'ListItem',position:2,name:title,item:origin+route}]});
 if(route.startsWith('/services/')&&route!=='/services/')graph.push({'@type':'Service',name:title,description,url:origin+route,provider:{'@id':firm['@id']},areaServed:{'@type':'Country',name:'India'}});
 return `<title>${headline}</title><meta name="description" content="${description}"><link rel="canonical" href="${origin}${route}"><meta name="robots" content="${['/thank-you/','/404.html'].includes(route)?'noindex, follow':'index, follow, max-image-preview:large'}"><meta property="og:site_name" content="${name}"><meta property="og:title" content="${headline}"><meta property="og:description" content="${description}"><meta property="og:type" content="website"><meta property="og:url" content="${origin}${route}"><meta property="og:image" content="${origin}/assets/social-preview.png"><meta property="og:image:secure_url" content="${origin}/assets/social-preview.png"><meta property="og:image:type" content="image/png"><meta property="og:image:width" content="1200"><meta property="og:image:height" content="630"><meta property="og:image:alt" content="PSB logo — P S B & Associates LLP, Chartered Accountants"><meta name="twitter:card" content="summary_large_image"><meta name="twitter:title" content="${headline}"><meta name="twitter:description" content="${description}"><meta name="twitter:image" content="${origin}/assets/social-preview.png"><link rel="apple-touch-icon" href="/assets/brand-icon.png"><script type="application/ld+json">${JSON.stringify({'@context':'https://schema.org','@graph':graph}).replaceAll('<','\\u003c')}</script>`;
}
