import fs from 'node:fs';
import path from 'node:path';
const walk=d=>fs.readdirSync(d,{withFileTypes:true}).flatMap(e=>e.name==='server'?[]:e.isDirectory()?walk(path.join(d,e.name)):[path.join(d,e.name)]);
const mime={'.html':'text/html; charset=utf-8','.css':'text/css; charset=utf-8','.js':'text/javascript; charset=utf-8','.json':'application/json; charset=utf-8','.webp':'image/webp','.jpg':'image/jpeg','.svg':'image/svg+xml','.xml':'application/xml','.txt':'text/plain'};
fs.mkdirSync('dist/assets',{recursive:true});fs.copyFileSync('data/announcements.json','dist/assets/announcements-snapshot.json');
const assets={};for(const filename of walk('dist')){if(filename.includes('.openai'))continue;const ext=path.extname(filename),binary=['.webp','.jpg','.png'].includes(ext);let route='/'+path.relative('dist',filename).replaceAll('\\','/');const entry={type:mime[ext]||'application/octet-stream',binary,body:fs.readFileSync(filename,binary?'base64':'utf8')};assets[route]=entry;if(route.endsWith('/index.html'))assets[route.slice(0,-10)]=entry;}
const feed=fs.readFileSync('lib/announcements.mjs','utf8').replace(/\bexport /g,'');
const source=`${feed}\nconst snapshot=${fs.readFileSync('data/announcements.json','utf8')};\nconst assets=${JSON.stringify(assets)};\nconst feedHandler=createFeedHandler(snapshot);\nexport default { async fetch(request,env,ctx){const url=new URL(request.url);if(!['GET','HEAD'].includes(request.method))return new Response('Method not allowed',{status:405,headers:{Allow:'GET, HEAD'}});if(url.pathname==='/api/announcements')return feedHandler(request);let asset=assets[url.pathname];if(!asset&&!url.pathname.endsWith('/')&&assets[url.pathname+'/'])return Response.redirect(url.origin+url.pathname+'/',308);if(!asset)return new Response('Page not found',{status:404});const body=asset.binary?Uint8Array.from(atob(asset.body),c=>c.charCodeAt(0)):asset.body;return new Response(request.method==='HEAD'?null:body,{headers:{'Content-Type':asset.type,'Cache-Control':url.pathname.startsWith('/assets/')?'public, max-age=3600':'public, max-age=60','X-Content-Type-Options':'nosniff','Referrer-Policy':'strict-origin-when-cross-origin'}});}};`;
fs.mkdirSync('dist/server',{recursive:true});fs.writeFileSync('dist/server/index.js',source);
console.log('Built self-contained Worker with announcements API and '+Object.keys(assets).length+' asset routes.');
